// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTX9_cF7G1Q_7vurtptkjlqV6GJJpx1Hc',
    appId: '1:881007028180:web:ae979046f78f49368d9841',
    messagingSenderId: '881007028180',
    projectId: 'playstationrental-6e032',
    authDomain: 'playstationrental-6e032.firebaseapp.com',
    storageBucket: 'playstationrental-6e032.firebasestorage.app',
    measurementId: 'G-042QRC87BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Tee6j1cw4lsH9Nf9PHn104RH77rxU8A',
    appId: '1:881007028180:android:0f19d7a2fd67ee618d9841',
    messagingSenderId: '881007028180',
    projectId: 'playstationrental-6e032',
    storageBucket: 'playstationrental-6e032.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlSiMkNdgfZbk2jv5ken0KXaA4GZ0ujoc',
    appId: '1:881007028180:ios:824adc5a1ea2c9ba8d9841',
    messagingSenderId: '881007028180',
    projectId: 'playstationrental-6e032',
    storageBucket: 'playstationrental-6e032.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlSiMkNdgfZbk2jv5ken0KXaA4GZ0ujoc',
    appId: '1:881007028180:ios:824adc5a1ea2c9ba8d9841',
    messagingSenderId: '881007028180',
    projectId: 'playstationrental-6e032',
    storageBucket: 'playstationrental-6e032.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTX9_cF7G1Q_7vurtptkjlqV6GJJpx1Hc',
    appId: '1:881007028180:web:001d80f9e6fedf708d9841',
    messagingSenderId: '881007028180',
    projectId: 'playstationrental-6e032',
    authDomain: 'playstationrental-6e032.firebaseapp.com',
    storageBucket: 'playstationrental-6e032.firebasestorage.app',
    measurementId: 'G-HCEVNXGSW6',
  );
}
